### ISSUE TITLE
Unable to build the whole file.

### ISSUE THREAD

**Issue by Phoenix269** [Pro/middleware_evaluation#1]
Hello,

I am unable to build the project and getting erros while make. I have attached the screenshot of the issue. Please help me to resolve it.
![Screenshot from 2020-04-11 15-50-28](https://user-images.githubusercontent.com/50555781/79045677-99341300-7c0c-11ea-9498-9f82e38024da.png)

**Comment by Pro** [comment]
Did you google for the error message `no module named six`?

There are literally millions of search results, just take the first one and you will magically find a solution.
